apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
      - job_name: 'frontend'
        static_configs:
          - targets: ['frontend.frontend.svc.cluster.local:80']
      - job_name: 'backend'
        static_configs:
          - targets: ['backend.backend.svc.cluster.local:5050']
      - job_name: 'mongodb'
        static_configs:
          - targets: ['mongodb.mongodb.svc.cluster.local:27017']
