apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - default
                - kube-system
                - kube-public
                - monitoring
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: kubernetes;https

      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)

      - job_name: 'kubernetes-cadvisor'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__meta_kubernetes_node_label_kubernetes_io_hostname]
            target_label: instance
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - default
                - kube-system
                - monitoring
                - frontend
                - backend
                - mongodb
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: .+

      - job_name: 'kubernetes-services'
        kubernetes_sd_configs:
          - role: service
            namespaces:
              names:
                - default
                - kube-system
                - monitoring
                - frontend
                - backend
                - mongodb
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app]
            action: keep
            regex: .+

      - job_name: 'kubernetes-ingresses'
        kubernetes_sd_configs:
          - role: ingress
            namespaces:
              names:
                - default
                - kube-system
                - monitoring
        relabel_configs:
          - source_labels: [__meta_kubernetes_ingress_label_app]
            action: keep
            regex: .+

      - job_name: 'frontend-backend-mongodb'
        static_configs:
          - targets: ['frontend.frontend.svc.cluster.local']
            labels:
              job: 'frontend'
          - targets: ['backend.backend.svc.cluster.local']
            labels:
              job: 'backend'
          - targets: ['mongodb.mongodb.svc.cluster.local']
            labels:
              job: 'mongodb'
